### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jerett-cc** [jerett-cc/ryujin#41]
Bugs:
- [ ] fix issue where, because we initialize the coarse level with the 'exact' coarse level approximation, we see little changes in tau for many future bricks, only changing when the exactness property takes effect. To fix this, we may need to write code that enables 1) random, but physical initial conditions, 2) initialize all bricks with the t=0 initial condition, and/or 3) enable user to specify initialization with even coarser levels, requiring the presence of many more level_structures.
- [ ] Why does the timer not print out all the things I expect to see timing on? Eg. higher levels?
- [x] The energy, for certain cycles (like cycle 3) is very large (like E = 1000)  at certain times when exact solution is only ~15. Is this a bug or a numerical instability? Fix in the projection operator? This is also referenced in #45.
- [x] Fix bug #42 

Code goals:
- [x] Write NS drag and Lift function
- [x] Make code faster, i.e. stop bricks already converged from running multiple times.
- [ ] Run the MGRIT and exact for an airfoil?
- [ ] Run MGRIT mach 3 two cylinder for T=20, rather than 5, to get multiple periods of eddy flow, with timing
- [x] Add condition OStreams for the t communicator, and the global: for use when we want information from certain t communicators, or if we want all processes to print their information to the ostream.
- [ ] Initialize with random data. The (unexpected) convergence could break doing this.
- [ ] Get code working in 3D?
- [ ] Add brick solution checkpointing option to Access(), this would allow for computations to re-start.
- [ ] Write some code for other time averaged QOI.
- [ ] Can we devise a PinT methods that uses multiple independent meshes and richardson extrapolation at common 'stopping points' to calculate the J(U,t) curve, under what conditions on J can this be done?
- [ ] Test a higher coarsening factor, what bricks do I get at the coarse levels.
- [x] Add tests for enforce_physicality, does_E_exceed
- [x] Rewrite enforce_physicality to look only at the local stencil, not n_locally_owned.
- [x] make exact data for the above, with timing
- [x] **Can we make the initialization stage sequential on only one processor, rather than starting over and over again on each time we need to generate a c-Point?**
